### ISSUE TITLE
Bug in dtool get_table_csv

### ISSUE THREAD

**Issue by Erotemic** [WildbookOrg/wildbook-ia#43]
One of the IBEIS users reported a bug a few months ago that I just looked into and fixed. 

The issue was that `ibs.dump_database_csv` was not working. Looking into the issue the problem was in dtool. 

In this repo, that issue exists on https://github.com/WildbookOrg/wildbook-ia/blob/master/wbia/dtool/sql_control.py#L3195

The following line: 

```python
        column_list, column_names = db.get_table_column_data(
            tablename, exclude_columns, rowids
        )
```

should be changed to 

```python
        column_list, column_names = db.get_table_column_data(
                tablename, exclude_columns=exclude_columns, rowids=rowids)
```

at some point the signature for `get_table_column_data` changed and added a new positional argument, which caused the "exclude_columns" arg to be send to the "columns" arg, thus nothing was exported. 

This probably isn't a critical issue in your guy's use case, but I figured I'd let you know. 

The patch for the ibeis version of dtool can be found here: https://github.com/Erotemic/dtool_ibeis/pull/2

**Comment by bluemellophone** [comment]
Thanks, Jon, for reporting this back to us.  It has been fixed.
